DROP TABLE IF EXISTS "users" CASCADE;
CREATE TABLE "users" (
    "user_gid" INT,
    "country" TEXT,
    "specialty" TEXT
);
INSERT INTO "users" VALUES
    (1,'GB','Cardiology'),
    (12,'GB','Cardiology'),
    (61,'US','Cardiology'),
    (4,'US','Cardiology'),
    (91,'US','Cardiology'),
    (16,'US','Cardiology'),
    (38,'DE','Cardiology'),
    (51,'US','Cardiology'),
    (7,'US','Cardiology'),
    (25,'DE','Cardiology'),
    (14,'ES','Cardiology'),
    (22,'FR','Cardiology'),
    (2,'US','Oncology'),
    (20,'FR','Oncology'),
    (8,'US','Oncology'),
    (11,'US','Oncology'),
    (3,'ES','Cardiology'),
    (134,'IT','Cardiology'),
    (43,'IT','Cardiology'),
    (13,'IT','Cardiology'),
    (6,'ES','Oncology'),
    (35,'ES','Oncology'),
    (10,'US','Cardiology'),
    (19,'US','Oncology'),
    (9,'US','Pediatrics'),
    (71,'US','Pediatrics'),
    (171,'US','Pediatrics'),
    (34,'US','Pediatrics'),
    (77,'US','Pediatrics'),
    (15,'IT','Cardiology'),
    (56,'IT','Cardiology'),
    (18,'IT','Oncology'),
    (23,'DE','Pediatrics'),
    (429,'ES','Pediatrics'),
    (110,'FR','Pediatrics'),
    (170,'IT','Pediatrics'),
    (44,'IT','Oncology'),
    (45,'CA','Oncology'),
    (86,'US','Pediatrics'),
    (36,'FR','Pediatrics'),
    (176,'GB','Pediatrics'),
    (100,'US','Pediatrics'),
    (78,'US','Pediatrics'),
    (209,'US','Oncology');
